### ISSUE TITLE
Update threefive!

### ISSUE THREAD

**Issue by futzu** [scunning1987/pois_reference_server#3]
Your threefive is super old, it's a lot better these days.
Don't use a zip file, pip install it. I really try to maintain backward compatibility.
Cool stuff by the way, I dig it. 

Adrian

**Comment by scunning1987** [comment]
Hi Adrian,

I know! I've been testing with the latest version, it's very good. I will update my version on my next commit

As for the pip install. That is how I installed threefive, but in order to make the library available in Lambda, you have to zip the contents and import to Lambda as a layer.

Thanks,
Scott

**Comment by futzu** [comment]
This is a great project man, I do stuff like this all the time and it never occurred to me to make a server, 
this is the way to go.
If you have a problem with something in threefive, just let me know, and I help you sort it out. 

This is super cool.
